### ISSUE TITLE
Error when doing email-manage.py -l

### ISSUE THREAD

**Issue by lepasserby** [rvojcik/iredmail-cli#2]
1) I have nginx, not apache (and in fact plan to disable it and manage cli-only
2) path is set correctly (email-manage.py does not throw path-related error)
3) iRedMail-0.9.4

Trying to run
email-manage.py -l

gives

Domains
Traceback (most recent call last):
  File "/usr/local/sbin/email-manage.py", line 456, in <module>
    search_database(args.domain, args.mailbox, args.search_string)
  File "/usr/local/sbin/email-manage.py", line 82, in search_database
    sql = "SELECT domain, description, transport, case when backupmx then 'yes' else 'no' end as 'Backup MX' FROM domain WHERE domain like '%" + search_string + "%'"
TypeError: cannot concatenate 'str' and 'bool' objects

**Comment by rvojcik** [comment]
Thx for your report. 

Yes your're right. It's bug in argument verification. 
You have tu use -l option in combination with -s or -m

email-manage.py -l -s '%'

or 

email-manage.py -l -m my@mailbox.tld

I'll fix it in new release

**Comment by alien4u** [comment]
I was able to fix this modifiying unicode(search_string).
Meaning replace every **'%" + search_string + "%'"** with **'%" + unicode(search_string) + "%'"**

Hope this help.

**Comment by bertalanimre** [comment]
So may I assume, this bug will never be fixed? :(
