### ISSUE TITLE
Problem with aliases (iRedMail 0.9.7+)

### ISSUE THREAD

**Issue by deseven** [rvojcik/iredmail-cli#4]
Looks like https://github.com/rvojcik/iredmail-cli/commit/0ef919edc01081eb7ee735ff9e1e476bc7600beb doesn't fix it completely, i get this error when i'm trying to get the list of aliases with `em -l -s something`:
```
Aliases
Traceback (most recent call last):
  File "/usr/local/bin/em", line 468, in <module>
    search_database(args.domain, args.mailbox, args.search_string)
  File "/usr/local/bin/em", line 92, in search_database
    result = send_sql_query(db_vmail, sql)
  File "/usr/local/bin/em", line 52, in send_sql_query
    dbresult.execute(query)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'goto' in 'field list'")
```

**Comment by rvojcik** [comment]
Hi, that's strange.

What is your version of IredMail ?

**Comment by deseven** [comment]
Hi. It's 0.9.7.  
They heavily modified db structure and removed `goto` column, check out [this part](https://docs.iredmail.org/upgrade.iredmail.0.9.6-0.9.7.html#drop-unused-sql-columns-and-records-in-vmailalias-table) of the upgrade manual.

**Comment by rvojcik** [comment]
Wow, thank you. I'm little bit behind current stable version. I look at it.

**Comment by rvojcik** [comment]
In next week I upgrade my mailserver to latest release and release new version of iredmail-cli.

Please  be patient :)

**Comment by rvojcik** [comment]
RC fix eaac0c2be483a8091296860532836de38cb61212

**Comment by deseven** [comment]
> Please be patient :)

Nothing terrible has happened, take your time! And anyway, thanks for your tool, it's very useful.

**Comment by uptimejeff** [comment]
This patch linked above resolved the issue for me.
iRedMail	0.9.9
iRedAdmin-Pro	3.1 (MySQL)

Thanks for this excellent tool 👍
